### ISSUE TITLE
Add @access to docblock.

### ISSUE THREAD

**Issue by Tjoosten** [IonAuth/IonAuth#29]
i was thinking. 
Should we add `@access` to the docblocks?

```
 /**
     * Class Constructor
     *
     * @access private
     * @param  string $driver The name of the mail driver
     * @param  array $config  The array of config values
     * @return void 
     */
```

**Comment by greydnls** [comment]
Is that standard practice in other projects?

**Comment by Tjoosten** [comment]
I don't know but i see sometimes on projects the @access attribute in the docblocks.

**Comment by Tjoosten** [comment]
And also add the `@param` in the docblocks. So Apigen can document the $variables in the function name.

I would like to do this if you want. 

CC @kayladnls @davidstanley01 @benedmunds

**Comment by benedmunds** [comment]
yea this is fine with me.

**Comment by Tjoosten** [comment]
https://github.com/IonAuth/IonAuth/commit/3c1972b28b020e8fb5cc6a510600c8010fee42b3 Throwing some @access attributes in the repo with this commit
