### ISSUE TITLE
Use ApiGen for docs

### ISSUE THREAD

**Issue by benedmunds** [IonAuth/IonAuth#6]

**Comment by Tjoosten** [comment]
Or jekyll? because it is GitHub pages supported. and can run on the project repo. by setting in a branch, named `gh_pages` what u think @benedmunds @kayladnls?

**Comment by kayladnls** [comment]
Is it only jekyll that can run on gh pages? I think sculpin might work too, or any flatfile site, really.

**Comment by Tjoosten** [comment]
flatsite website to? but if you want to use flat you can better use jekyll. sculpin im not so sure about it

**Comment by Tjoosten** [comment]
First version is up in the docs repo. Only we need regenerate that sometimes.
